// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwv_fxl8czRhHWnPFRyXdXmGPCyF2qItA',
    appId: '1:760357776543:web:1a82dd1319de51fcba06aa',
    messagingSenderId: '760357776543',
    projectId: 'iota-f0f8a',
    authDomain: 'iota-f0f8a.firebaseapp.com',
    storageBucket: 'iota-f0f8a.appspot.com',
    measurementId: 'G-F6J4L963GW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4Ec4JpUx1Mj5FN5kzCFg1NaltMVx7E7M',
    appId: '1:760357776543:android:78ae70a09acb1ce1ba06aa',
    messagingSenderId: '760357776543',
    projectId: 'iota-f0f8a',
    storageBucket: 'iota-f0f8a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8pFdCI_rSVuAOw4QU-WkxKEITvH2xtd0',
    appId: '1:760357776543:ios:dfee8e6a5260bf60ba06aa',
    messagingSenderId: '760357776543',
    projectId: 'iota-f0f8a',
    storageBucket: 'iota-f0f8a.appspot.com',
    iosBundleId: 'com.example.iota',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8pFdCI_rSVuAOw4QU-WkxKEITvH2xtd0',
    appId: '1:760357776543:ios:34260dd686ad3348ba06aa',
    messagingSenderId: '760357776543',
    projectId: 'iota-f0f8a',
    storageBucket: 'iota-f0f8a.appspot.com',
    iosBundleId: 'com.example.iota.RunnerTests',
  );
}
